# Stored inside limine-uefi-cd.bin (FAT El Torito volume).
# `boot()` therefore resolves to this same FAT volume under UEFI.
timeout: 3
serial: yes
interface_branding: ATMKoala v0.9 UEFI

/ATMKoala v0.9 [Graphical 800x600]
    protocol: multiboot2
    path: boot():/kernel.bin
    resolution: 800x600x32

/ATMKoala v0.9 [Text Mode]
    protocol: multiboot2
    path: boot():/kernel.bin
    cmdline: novbe text
    textmode: yes
