from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "image_fixtures.h"
W, H = 96, 64


def render(kind: str) -> Image.Image:
    im = Image.new("RGBA", (W, H), (18, 20, 25, 255))
    px = im.load()
    for y in range(H):
        for x in range(W):
            tile = ((x // 8) + (y // 8)) & 1
            base = 24 if tile else 34
            if kind == "png":
                px[x, y] = (base + x * 2, base + y * 2, 66 + (x + y) // 5, 255 if (x + y) % 13 else 160)
            else:
                px[x, y] = (base + y * 2, 55 + x, base + 35, 255)
    d = ImageDraw.Draw(im)
    d.rectangle((5, 5, W - 6, H - 6), outline=(239, 218, 176, 255), width=2)
    d.polygon([(13, H - 13), (37, 24), (52, 42), (65, 17), (W - 14, H - 13)], fill=(91, 166, 106, 255))
    d.ellipse((W - 27, 10, W - 16, 21), fill=(241, 187, 94, 255))
    d.text((12, 9), "EXP", fill=(245, 245, 239, 255))
    return im


def format_bytes(name: str, data: bytes) -> str:
    rows = []
    for i in range(0, len(data), 12):
        rows.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i+12]) + ",")
    body = "\n".join(rows)
    return f"static const unsigned char {name}[] = {{\n{body}\n}};\n#define {name.upper()}_LEN ((unsigned int)sizeof({name}))\n"


png_path = ROOT / "tools" / "exp-sample.png"
jpg_path = ROOT / "tools" / "exp-sample.jpg"
render("png").save(png_path, "PNG", optimize=False)
render("jpeg").convert("RGB").save(jpg_path, "JPEG", quality=86, optimize=False, progressive=False)
png = png_path.read_bytes()
jpeg = jpg_path.read_bytes()
OUT.write_text(
    "#ifndef ATM_IMAGE_FIXTURES_H\n#define ATM_IMAGE_FIXTURES_H\n\n"
    "/* Generated by tools/gen_image_fixtures.py: 96x64 decoder regression images. */\n"
    + format_bytes("atm_fixture_png", png)
    + "\n"
    + format_bytes("atm_fixture_jpeg", jpeg)
    + "\n#endif\n"
)
print(f"wrote {OUT}: PNG={len(png)} bytes JPEG={len(jpeg)} bytes")
